"""HTML report templates for viz-mcp."""

from __future__ import annotations


def get_report_template() -> str:
    """Return the Jinja2 HTML report template string."""
    return """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ title }}</title>
<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
<style>
  *, *::before, *::after { box-sizing: border-box; }
  body {
    margin: 0; padding: 32px;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #fafbfc; color: #24292e; line-height: 1.6;
  }
  .report-header {
    border-bottom: 3px solid #1a1a2e;
    padding-bottom: 12px; margin-bottom: 32px;
  }
  .report-header h1 { margin: 0; font-size: 28px; color: #1a1a2e; }
  .report-header .timestamp {
    font-size: 13px; color: #6a737d; margin-top: 4px;
  }
  .section { margin-bottom: 36px; }
  .section h2 { font-size: 20px; color: #1a1a2e; margin-bottom: 12px; }
  .section-text { max-width: 800px; }
  .section-text p { margin: 0 0 12px; }
  .chart-container {
    background: #fff; border: 1px solid #e1e4e8;
    border-radius: 6px; padding: 16px;
  }
  .table-container {
    overflow-x: auto; background: #fff; border: 1px solid #e1e4e8;
    border-radius: 6px; padding: 16px;
  }
  .footer {
    margin-top: 48px; padding-top: 16px;
    border-top: 1px solid #e1e4e8; font-size: 12px; color: #6a737d;
  }
</style>
</head>
<body>
<div class="report-header">
  <h1>{{ title }}</h1>
  <div class="timestamp">Generated by viz-mcp</div>
</div>
{% for section in sections %}
<div class="section">
  {% if section.type == "text" %}
    {% if section.title %}<h2>{{ section.title }}</h2>{% endif %}
    <div class="section-text">{{ section.content }}</div>
  {% elif section.type == "table" %}
    <div class="table-container">{{ section.html | safe }}</div>
  {% elif section.type == "chart" %}
    {% if section.title %}<h2>{{ section.title }}</h2>{% endif %}
    <div class="chart-container">{{ section.html | safe }}</div>
  {% endif %}
</div>
{% endfor %}
<div class="footer">Self-contained report &middot; Open in any browser</div>
</body>
</html>"""
