"""Shared utilities and testing infrastructure for MCP server projects."""

from mcpanvil.agent_remediation import (
    format_agent_exception_remediation,
    mcp_remediation_wrapper,
    mcp_tool_error_with_remediation,
)
from mcpanvil.auth import HttpAccessTokenAuth
from mcpanvil.cli import (
    JsonOption,
    PollTimeout,
    SuggestingTyperGroup,
    create_cli_app,
    echo_result,
    poll_until,
    run_cli,
)
from mcpanvil.config import MCPSettings
from mcpanvil.credential_chain import CachedResolver
from mcpanvil.credentials import (
    CredentialAuditEvent,
    CredentialCandidate,
    CredentialResult,
    UsernamePassword,
    UsernamePasswordCredentialProvider,
)
from mcpanvil.doctor import DoctorReport
from mcpanvil.doctor import run as doctor_run
from mcpanvil.dual_mode import CliContext, build_cli_from_mcp, dual_mode_tool
from mcpanvil.env import load_env
from mcpanvil.health import health_resource
from mcpanvil.hints import HintRegistry, ToolHint
from mcpanvil.http import (
    ArgSpec,
    AsyncRetryingHttpxClient,
    ConditionalGetResult,
    ETagStore,
    HttpClientConfig,
    HttpClientError,
    RetryingHttpxClient,
    add_health_route,
    apply_conditional_headers,
    build_arg_parser,
    conditional_get,
    create_http_app,
    record_response,
    settings_from_args,
    user_agent,
)
from mcpanvil.logging import (
    DEFAULT_NOISY_LOGGERS,
    LOG_CHANNEL_ACCESS,
    LOG_CHANNEL_APP,
    LOG_CHANNEL_TRACE,
    LOG_CHANNEL_TRANSCRIPT,
    TRACE_LOGGER_NAME,
    compute_error_fingerprint,
    configure_trace_channel,
    format_exception_for_trace,
    get_trace_logger,
    log_access_event,
    log_timing_event,
    log_trace_event,
    log_transcript_event,
    mcp_log_access,
    mcp_log_trace,
    mcp_log_transcript,
    redact_config_from_settings,
    sanitize_transcript_value,
    setup_logging,
    suppress_noisy_loggers,
    suppress_ssl_warnings,
    timed_operation,
    transcript_should_log,
)
from mcpanvil.lookup_cache import LookupCache, NameIdResolver
from mcpanvil.plugin_schema import PluginConfig
from mcpanvil.progress import OperationStates, PollResult, poll_with_progress
from mcpanvil.service_discovery import (
    AuthType,
    NetBoxServiceDiscovery,
    ServiceEndpoint,
    SiteServices,
)
from mcpanvil.sites import SiteConfig, SiteManager
from mcpanvil.version import get_version

__all__ = [
    "DEFAULT_NOISY_LOGGERS",
    "LOG_CHANNEL_ACCESS",
    "LOG_CHANNEL_APP",
    "LOG_CHANNEL_TRACE",
    "LOG_CHANNEL_TRANSCRIPT",
    "TRACE_LOGGER_NAME",
    "ArgSpec",
    "AsyncRetryingHttpxClient",
    "AuthType",
    "CachedResolver",
    "CliContext",
    "ConditionalGetResult",
    "CredentialAuditEvent",
    "CredentialCandidate",
    "CredentialResult",
    "DoctorReport",
    "ETagStore",
    "HintRegistry",
    "HttpAccessTokenAuth",
    "HttpClientConfig",
    "HttpClientError",
    "JsonOption",
    "LookupCache",
    "MCPSettings",
    "NameIdResolver",
    "NetBoxServiceDiscovery",
    "OperationStates",
    "PluginConfig",
    "PollResult",
    "PollTimeout",
    "RetryingHttpxClient",
    "ServiceEndpoint",
    "SiteConfig",
    "SiteManager",
    "SiteServices",
    "SuggestingTyperGroup",
    "ToolHint",
    "UsernamePassword",
    "UsernamePasswordCredentialProvider",
    "add_health_route",
    "apply_conditional_headers",
    "build_arg_parser",
    "build_cli_from_mcp",
    "compute_error_fingerprint",
    "conditional_get",
    "configure_trace_channel",
    "create_cli_app",
    "create_http_app",
    "doctor_run",
    "dual_mode_tool",
    "echo_result",
    "format_agent_exception_remediation",
    "format_exception_for_trace",
    "get_trace_logger",
    "get_version",
    "health_resource",
    "load_env",
    "log_access_event",
    "log_timing_event",
    "log_trace_event",
    "log_transcript_event",
    "mcp_log_access",
    "mcp_log_trace",
    "mcp_log_transcript",
    "mcp_remediation_wrapper",
    "mcp_tool_error_with_remediation",
    "poll_until",
    "poll_with_progress",
    "record_response",
    "redact_config_from_settings",
    "run_cli",
    "sanitize_transcript_value",
    "settings_from_args",
    "setup_logging",
    "suppress_noisy_loggers",
    "suppress_ssl_warnings",
    "timed_operation",
    "transcript_should_log",
    "user_agent",
]
