# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ufm_mcp.proto import health_pb2 as health__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in health_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthServiceStub(object):
    """Health service for fabric health monitoring
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFabricHealth = channel.unary_unary(
                '/topaz.health.HealthService/GetFabricHealth',
                request_serializer=health__pb2.GetFabricHealthRequest.SerializeToString,
                response_deserializer=health__pb2.FabricHealthResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/topaz.health.HealthService/ListCollections',
                request_serializer=health__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=health__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.GetCollection = channel.unary_unary(
                '/topaz.health.HealthService/GetCollection',
                request_serializer=health__pb2.GetCollectionRequest.SerializeToString,
                response_deserializer=health__pb2.GetCollectionResponse.FromString,
                _registered_method=True)
        self.TriggerIbdiagnetCollection = channel.unary_unary(
                '/topaz.health.HealthService/TriggerIbdiagnetCollection',
                request_serializer=health__pb2.TriggerIbdiagnetRequest.SerializeToString,
                response_deserializer=health__pb2.TriggerIbdiagnetResponse.FromString,
                _registered_method=True)
        self.TriggerTopologyCollection = channel.unary_unary(
                '/topaz.health.HealthService/TriggerTopologyCollection',
                request_serializer=health__pb2.TriggerTopologyRequest.SerializeToString,
                response_deserializer=health__pb2.TriggerTopologyResponse.FromString,
                _registered_method=True)
        self.ListSwitches = channel.unary_unary(
                '/topaz.health.HealthService/ListSwitches',
                request_serializer=health__pb2.ListSwitchesRequest.SerializeToString,
                response_deserializer=health__pb2.ListSwitchesResponse.FromString,
                _registered_method=True)
        self.ListPortCounters = channel.unary_unary(
                '/topaz.health.HealthService/ListPortCounters',
                request_serializer=health__pb2.ListPortCountersRequest.SerializeToString,
                response_deserializer=health__pb2.ListPortCountersResponse.FromString,
                _registered_method=True)
        self.ListCables = channel.unary_unary(
                '/topaz.health.HealthService/ListCables',
                request_serializer=health__pb2.ListCablesRequest.SerializeToString,
                response_deserializer=health__pb2.ListCablesResponse.FromString,
                _registered_method=True)
        self.GetCollectionStatus = channel.unary_unary(
                '/topaz.health.HealthService/GetCollectionStatus',
                request_serializer=health__pb2.GetCollectionStatusRequest.SerializeToString,
                response_deserializer=health__pb2.GetCollectionStatusResponse.FromString,
                _registered_method=True)
        self.ImportCollection = channel.unary_unary(
                '/topaz.health.HealthService/ImportCollection',
                request_serializer=health__pb2.ImportCollectionRequest.SerializeToString,
                response_deserializer=health__pb2.ImportCollectionResponse.FromString,
                _registered_method=True)
        self.UploadIbdiagnet = channel.unary_unary(
                '/topaz.health.HealthService/UploadIbdiagnet',
                request_serializer=health__pb2.UploadIbdiagnetRequest.SerializeToString,
                response_deserializer=health__pb2.ImportCollectionResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """Health service for fabric health monitoring
    """

    def GetFabricHealth(self, request, context):
        """Get current fabric health status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """List ibdiagnet collections
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollection(self, request, context):
        """Get a specific collection by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerIbdiagnetCollection(self, request, context):
        """Trigger a new ibdiagnet collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerTopologyCollection(self, request, context):
        """Trigger a new topology collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSwitches(self, request, context):
        """List switches with aggregated error info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPortCounters(self, request, context):
        """List port counters with full detail
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCables(self, request, context):
        """List cable/transceiver info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionStatus(self, request, context):
        """Get current collection status (running/idle)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportCollection(self, request, context):
        """Import an ibdiagnet collection (from CLI or external tool)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadIbdiagnet(self, request, context):
        """Upload raw ibdiagnet tarball for server-side parsing and import
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFabricHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFabricHealth,
                    request_deserializer=health__pb2.GetFabricHealthRequest.FromString,
                    response_serializer=health__pb2.FabricHealthResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=health__pb2.ListCollectionsRequest.FromString,
                    response_serializer=health__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'GetCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollection,
                    request_deserializer=health__pb2.GetCollectionRequest.FromString,
                    response_serializer=health__pb2.GetCollectionResponse.SerializeToString,
            ),
            'TriggerIbdiagnetCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerIbdiagnetCollection,
                    request_deserializer=health__pb2.TriggerIbdiagnetRequest.FromString,
                    response_serializer=health__pb2.TriggerIbdiagnetResponse.SerializeToString,
            ),
            'TriggerTopologyCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerTopologyCollection,
                    request_deserializer=health__pb2.TriggerTopologyRequest.FromString,
                    response_serializer=health__pb2.TriggerTopologyResponse.SerializeToString,
            ),
            'ListSwitches': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSwitches,
                    request_deserializer=health__pb2.ListSwitchesRequest.FromString,
                    response_serializer=health__pb2.ListSwitchesResponse.SerializeToString,
            ),
            'ListPortCounters': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPortCounters,
                    request_deserializer=health__pb2.ListPortCountersRequest.FromString,
                    response_serializer=health__pb2.ListPortCountersResponse.SerializeToString,
            ),
            'ListCables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCables,
                    request_deserializer=health__pb2.ListCablesRequest.FromString,
                    response_serializer=health__pb2.ListCablesResponse.SerializeToString,
            ),
            'GetCollectionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionStatus,
                    request_deserializer=health__pb2.GetCollectionStatusRequest.FromString,
                    response_serializer=health__pb2.GetCollectionStatusResponse.SerializeToString,
            ),
            'ImportCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportCollection,
                    request_deserializer=health__pb2.ImportCollectionRequest.FromString,
                    response_serializer=health__pb2.ImportCollectionResponse.SerializeToString,
            ),
            'UploadIbdiagnet': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadIbdiagnet,
                    request_deserializer=health__pb2.UploadIbdiagnetRequest.FromString,
                    response_serializer=health__pb2.ImportCollectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'topaz.health.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('topaz.health.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """Health service for fabric health monitoring
    """

    @staticmethod
    def GetFabricHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topaz.health.HealthService/GetFabricHealth',
            health__pb2.GetFabricHealthRequest.SerializeToString,
            health__pb2.FabricHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topaz.health.HealthService/ListCollections',
            health__pb2.ListCollectionsRequest.SerializeToString,
            health__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topaz.health.HealthService/GetCollection',
            health__pb2.GetCollectionRequest.SerializeToString,
            health__pb2.GetCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerIbdiagnetCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topaz.health.HealthService/TriggerIbdiagnetCollection',
            health__pb2.TriggerIbdiagnetRequest.SerializeToString,
            health__pb2.TriggerIbdiagnetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerTopologyCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topaz.health.HealthService/TriggerTopologyCollection',
            health__pb2.TriggerTopologyRequest.SerializeToString,
            health__pb2.TriggerTopologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSwitches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topaz.health.HealthService/ListSwitches',
            health__pb2.ListSwitchesRequest.SerializeToString,
            health__pb2.ListSwitchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPortCounters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topaz.health.HealthService/ListPortCounters',
            health__pb2.ListPortCountersRequest.SerializeToString,
            health__pb2.ListPortCountersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topaz.health.HealthService/ListCables',
            health__pb2.ListCablesRequest.SerializeToString,
            health__pb2.ListCablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topaz.health.HealthService/GetCollectionStatus',
            health__pb2.GetCollectionStatusRequest.SerializeToString,
            health__pb2.GetCollectionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topaz.health.HealthService/ImportCollection',
            health__pb2.ImportCollectionRequest.SerializeToString,
            health__pb2.ImportCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadIbdiagnet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/topaz.health.HealthService/UploadIbdiagnet',
            health__pb2.UploadIbdiagnetRequest.SerializeToString,
            health__pb2.ImportCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
