#!/bin/bash
# Setup script for E2E testing environment
# This script helps configure environment variables for e2e testing

set -e

echo "🔧 AWX MCP Server E2E Testing Setup"
echo "=================================="
echo

# Check if we're in the right directory
if [[ ! -f "pyproject.toml" ]] || [[ ! -d "tests" ]]; then
    echo "❌ Error: Run this script from the awx-mcp directory"
    exit 1
fi

echo "📝 This script will help you set up environment variables for E2E testing."
echo "⚠️  WARNING: E2E tests should NEVER be run against production AWX instances!"
echo

# Check for existing .env file
if [[ -f ".env" ]]; then
    echo "⚠️  Found existing .env file. Backing it up to .env.backup"
    cp .env .env.backup
    echo
fi

# Collect AWX connection details
echo "🔗 AWX Connection Details"
echo "------------------------"

read -p "AWX Host URL (e.g., https://awx.example.com): " awx_host
if [[ -z "$awx_host" ]]; then
    echo "❌ Error: AWX host is required"
    exit 1
fi

read -p "AWX Token: " awx_token
if [[ -z "$awx_token" ]]; then
    echo "❌ Error: AWX token is required"
    exit 1
fi

echo
echo "🧪 Test Resource IDs (optional - press Enter to skip)"
echo "---------------------------------------------------"

read -p "Test Organization ID: " org_id
read -p "Test Project ID: " project_id
read -p "Test Inventory ID: " inventory_id

# Test connection
echo
echo "🔍 Testing connection..."
if command -v curl &> /dev/null; then
    response=$(curl -s -w "%{http_code}" -H "Authorization: Bearer $awx_token" "$awx_host/api/v2/ping" -o /dev/null)
    if [[ "$response" == "200" ]]; then
        echo "✅ Connection successful!"
    else
        echo "❌ Connection failed (HTTP $response). Please check your credentials."
        exit 1
    fi
else
    echo "⚠️  curl not found, skipping connection test"
fi

# Create .env file
echo
echo "📝 Creating .env file..."

cat > .env << EOF
# AWX MCP Server E2E Testing Configuration
# Generated by setup_e2e.sh on $(date)

# AWX Connection
AWX_HOST=$awx_host
AWX_TOKEN=$awx_token

# Test Resources (optional)
$( [[ -n "$org_id" ]] && echo "E2E_TEST_ORG_ID=$org_id" )
$( [[ -n "$project_id" ]] && echo "E2E_TEST_PROJECT_ID=$project_id" )
$( [[ -n "$inventory_id" ]] && echo "E2E_TEST_INVENTORY_ID=$inventory_id" )

# E2E Test Control
E2E_TEST_ENABLED=true
E2E_ALLOW_JOB_LAUNCH=false

# Logging
LOG_LEVEL=INFO
EOF

echo "✅ .env file created successfully!"
echo
echo "🚀 Next Steps:"
echo "-------------"
echo "1. Review the .env file and adjust settings as needed"
echo "2. Run unit tests: uv run pytest tests/ -q"
echo "3. Run e2e tests: uv run pytest tests/test_e2e.py -v"
echo "4. For job launch testing, set E2E_ALLOW_JOB_LAUNCH=true (⚠️  USE WITH CAUTION)"
echo
echo "📚 See E2E_TESTING.md for detailed documentation"
echo
echo "🔒 Security Reminder:"
echo "- Never commit .env files to version control"
echo "- Never run e2e tests against production AWX instances"
echo "- Use dedicated test instances for e2e testing"